name: countries_app
description: Countries Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.3
  dio: ^5.3.2
  filter_list: ^1.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.2
  maps_launcher: ^2.2.1
  retrofit: ^4.0.1

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  retrofit_generator: ^8.1.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
